# documentation: https://github.com/g0ldyy/comet
# slogan: The only Stremio addon that can Proxy Debrid Streams to allow use of the Debrid Service on multiple IPs at the same time on the same account!
# tags: comet
# logo: svgs/comet.svg
# port: 8000

version: "3.8"

services:
  comet:
    image: g0ldyy/comet
    platform: linux/amd64
    restart: unless-stopped
    expose:
      - 8000
    volumes:
      - comet_data:/data
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          '"""import requests;print(requests.get(''http://localhost:8000\'').status_code)"""',
        ]
      timeout: 5s
      interval: 60s
      retries: 3
    depends_on:
      - jackettindexer
      - warp
    environment:
      - SERVICE_FQDN_COMET
      - ADDON_ID=stremio.comet.fastselfhost
      - ADDON_NAME=Comet
      - FASTAPI_HOST=0.0.0.0
      - FASTAPI_PORT=8000
      - FASTAPI_WORKERS=1
      - DASHBOARD_ADMIN_PASSWORD=${SERVICE_PASSWORD_ADMINPASSWORD}
      - DATABASE_TYPE=sqlite
      - DATABASE_URL=
      - DATABASE_PATH=data/comet.db
      - CACHE_TTL=86400
      - DEBRID_PROXY_URL=http://warp:1080
      - INDEXER_MANAGER_TYPE=jackett
      - INDEXER_MANAGER_URL=http://jackettindexer:9117
      - INDEXER_MANAGER_API_KEY=${INDEXER_MANAGER_API_KEY}
      - INDEXER_MANAGER_TIMEOUT=60
      - INDEXER_MANAGER_INDEXERS=${INDEXER_MANAGER_INDEXERS:-[]}
      - GET_TORRENT_TIMEOUT=5
      - ZILEAN_URL=None
      - ZILEAN_TAKE_FIRST=500
      - SCRAPE_TORRENTIO=${SCRAPE_TORRENTIO:-True}
      - PROXY_DEBRID_STREAM=${PROXY_DEBRID_STREAM:-True}
      - PROXY_DEBRID_STREAM_PASSWORD=${SERVICE_PASSWORD_STREAMPASSWORD}
      - PROXY_DEBRID_STREAM_MAX_CONNECTIONS=100
      - PROXY_DEBRID_STREAM_DEBRID_DEFAULT_SERVICE=${PROXY_DEBRID_STREAM_DEBRID_DEFAULT_SERVICE:-realdebrid}
      - PROXY_DEBRID_STREAM_DEBRID_DEFAULT_APIKEY=${DEBRID_API_KEY}
      - TITLE_MATCH_CHECK=True
      - CUSTOM_HEADER_HTML=None

  warp:
    image: caomingjun/warp
    restart: always
    expose:
      - 1080
    environment:
      - WARP_SLEEP=2
      # - WARP_LICENSE_KEY= # optional
    cap_add:
      # Docker already have them, these are for podman users
      - MKNOD
      - AUDIT_WRITE
      # additional required cap for warp, both for podman and docker
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - warp_data:/var/lib/cloudflare-warp

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - SERVICE_FQDN_PROWLARR
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - prowlarr_data:/config
    expose:
      - 9696
    restart: unless-stopped
