services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    environment:
      - SERVICE_FQDN_PLEX
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
      - PLEX_CLAIM= #optional
    expose:
      - 32400
    ports:
      - 32400:32400
    env_file:
      - .env
    volumes:
      - ${ROOT}/plex/data:/config
      - ${ROOT}/downloads/tv:/downloads/tv
      - ${ROOT}/downloads/movies:/downloads/movies
    restart: unless-stopped
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    expose:
      - 8096
    ports:
      - 8096:8096
    env_file:
      - .env
    volumes:
      - ${ROOT}/jellyfin/config:/config
      - ${ROOT}/jellyfin/cache:/cache
      - ${ROOT}/downloads/tv:/downloads/tv
      - ${ROOT}/downloads/movies:/downloads/movies
    restart: "unless-stopped"
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${ROOT}/bazarr/config:/config
      - ${ROOT}/downloads/movies:/movies
      - ${ROOT}/downloads/tv:/tv
    expose:
      - 6767
    ports:
      - 6767:6767
    restart: unless-stopped
  rdtclient:
    image: rogerfar/rdtclient
    container_name: rdtclient
    environment:
      - SERVICE_FQDN_RDTCLIENT
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    env_file:
      - .env
    volumes:
      - ${ROOT}/rdt/data:/data/db
      - ${ROOT}/downloads:/data/downloads
    logging:
      driver: json-file
      options:
        max-size: 10m
    expose:
      - 6500
    ports:
      - 6500:6500
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - SERVICE_FQDN_RADARR
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    env_file:
      - .env
    volumes:
      - ${ROOT}/radarr/data:/config
      - ${ROOT}/downloads/movies:/movies #optional
      - ${ROOT}/downloads:/downloads #optional
    expose:
      - 7878
    ports:
      - 7878:7878
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - SERVICE_FQDN_SONARR
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    env_file:
      - .env
    volumes:
      - ${ROOT}/sonarr/data:/config
      - ${ROOT}/downloads/tv:/tv
      - ${ROOT}/downloads:/downloads
    expose:
      - 8989
    ports:
      - 8989:8989
    restart: unless-stopped
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - SERVICE_FQDN_PROWLARR
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    env_file:
      - .env
    volumes:
      - ${ROOT}/prowlarr/data:/config
    expose:
      - 9696
    ports:
      - 9696:9696
    restart: unless-stopped
