services:
  macos:
    image: dockurr/macos
    container_name: macos
    environment:
      - VERSION=15
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389
    stop_grace_period: 2m
    volumes:
      - ./macos:/storage
      - /:/shared
volumes:
  macos_data: null
