services:
  windows:
    image: dockurr/macos
    container_name: macos
    environment:
      - VERSION=15
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    expose:
      - 8006
      - 3389
    stop_grace_period: 2m
    volumes:
      - ./macos:/storage
      - /:/shared
volumes:
  windows_data: null
