services:
  android-build-env:
    image: yokowasis/android-build-env:latest
    container_name: android-build-env
    env_file:
      - .env
    volumes:
      - ${WORKSPACE}:/workspace
      - ${WORKSPACE}:/var/www/html
      - home:/root
    ports:
      - "4080:8000"
      - "4081:80"
      - "9003:9003"
    working_dir: /workspace
    restart: unless-stopped
    tty: true
    stdin_open: true

  mysql:
    image: mysql:8.0
    container_name: mysql-service
    environment:
      MYSQL_ROOT_PASSWORD: 123123
      MYSQL_DATABASE: app_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    expose:
      - 3306
    volumes:
      - mysql_data:/var/lib/mysql # Persist MySQL data

  postgres:
    image: postgres:15
    container_name: postgres-service
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist PostgreSQL data

volumes:
  mysql_data:
  postgres_data:
  home:
