services:
  android-build-env:
    image: yokowasis/android-build-env:latest
    container_name: android-build-env
    env_file:
      - .env
    volumes:
      - ${WORKSPACE}:/workspace
      - ${HOMEDIR}:/root
    ports:
      - "5173:5173"
      - "5174:5174"
      - "5175:5175"
      - "5176:5176"
      - "5177:5177"
      - "5178:5178"
      - "5179:5179"
      - "8000:8000"
      - "80:80"
      - "9003:9003"
      - "3000:3000"
      - "3001:3001"
      - "8976:8976"
    working_dir: /workspace
    restart: unless-stopped
    tty: true
    stdin_open: true

  mysql:
    image: mysql:8.0
    container_name: mysql-service
    environment:
      MYSQL_ROOT_PASSWORD: 123123
      MYSQL_DATABASE: app_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    restart: unless-stopped
    expose:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql # Persist MySQL data

  postgres:
    image: pgvector/pgvector:pg15
    container_name: postgres-service
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ${WORKSPACE}:/workspace

  phppgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    container_name: phppgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=yokowasis@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=123123
    ports:
      - 5050:80
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - mysql
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=123123
    ports:
      - 6060:80

volumes:
  mysql_data:
  postgres_data:
  pgadmin_data:
