# documentation: https://code.visualstudio.com/docs
# slogan: Unofficial Microsoft VSCode Docker Image. Only for personal use.
# tags: msvscode
# logo: svgs/msvscode.svg
# port: 8080

services:
  vscode:
    image: yokowasis/msvscode
    expose:
      - 8080
    environment:
      - SERVICE_FQDN_MSVSCODE
      - TOKEN=${SERVICE_PASSWORD_TOKEN}
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://127.0.0.1:8080/?tkn=${SERVICE_PASSWORD_TOKEN}",
        ]
      timeout: 5s
      interval: 60s
      retries: 3
    restart: unless-stopped
    volumes:
      - msvscode_data:/root
      - mariadb_data:/var/lib/mysql
      - apache_data:/var/www/html
