services:
  wordpress:
    image: wordpress:latest
    volumes:
      - wordpress-files:/var/www/html
      - conf-files:/etc/apache2/sites-available
    environment:
      - SERVICE_FQDN_WORDPRESS
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=${DB_USER}
      - WORDPRESS_DB_PASSWORD=${DB_PASS}
      - WORDPRESS_DB_NAME=${DB_NAME}
    expose:
      - 80
    depends_on:
      - mariadb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1"]
      interval: 2s
      timeout: 10s
      retries: 10
  mariadb:
    image: mariadb:11
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_PASS}
      - MARIADB_DATABASE=${DB_NAME}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASS}
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 20s
      retries: 10
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - SERVICE_FQDN_PHPMYADMIN
      - PMA_HOST=mariadb
      - PMA_USER=${DB_USER}
      - PMA_PASSWORD=${DB_PASS}
    expose:
      - 80
    depends_on:
      - mariadb

volumes:
  wordpress-files:
  mariadb-data:
  conf-files:
