# add to .bashrc 
# export RCLONE_CONF_BASE64=$(base64 ~/.config/rclone/rclone.conf)

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 0:0
    expose:
      - 8096
    ports:
      - 8096:8096
    env_file:
      - .env
    volumes:
      - ${ROOT}/jellyfin/config:/config
      - ${ROOT}/jellyfin/cache:/cache
      - ${ROOT}/downloads/tv:/downloads/tv
      - ${ROOT}/downloads/movies:/downloads/movies
      - gdrive:/plexdrive
    restart: "unless-stopped"
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Etc/UTC
    volumes:
      - ${ROOT}/bazarr/config:/config
      - ${ROOT}/downloads/movies:/movies
      - ${ROOT}/downloads/tv:/tv
    expose:
      - 6767
    ports:
      - 6767:6767
    restart: unless-stopped
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=0          
      - PGID=0          
      - TZ=Europe/London   
      - WEBUI_PORT=8080
    volumes:
      - ${ROOT}/qbittorrent_config:/config   
      - ${ROOT}/downloads:/downloads  
    ports:
      - 8080:8080          
      - 6881:6881          
      - 6881:6881/udp      
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - SERVICE_FQDN_RADARR
      - PUID=0
      - PGID=0
      - TZ=Etc/UTC
    env_file:
      - .env
    volumes:
      - ${ROOT}/radarr/data:/config
      - ${ROOT}/downloads/movies:/movies 
      - ${ROOT}/downloads:/downloads 
      - gdrive:/plexdrive
    expose:
      - 7878
    ports:
      - 7878:7878
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - SERVICE_FQDN_SONARR
      - PUID=0
      - PGID=0
      - TZ=Etc/UTC
    env_file:
      - .env
    volumes:
      - ${ROOT}/sonarr/data:/config
      - ${ROOT}/downloads/tv:/tv
      - ${ROOT}/downloads:/downloads
      - gdrive:/plexdrive
    expose:
      - 8989
    ports:
      - 8989:8989
    restart: unless-stopped
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - SERVICE_FQDN_PROWLARR
      - PUID=0
      - PGID=0
      - TZ=Etc/UTC
    env_file:
      - .env
    volumes:
      - ${ROOT}/prowlarr/data:/config
    expose:
      - 9696
    ports:
      - 9696:9696
    restart: unless-stopped

volumes:
  gdrive:
    driver: sapk/plugin-rclone
    driver_opts:
      config: "${RCLONE_CONF_BASE64}"
      remote: "gdrive:/PLEX"