services:
  web:
    image: php:8.1-apache
    container_name: lamp_web
    ports:
      - "8080:80"
    volumes:
      - ./html:/var/www/html
      - ./php-config/php.ini:/usr/local/etc/php/php.ini
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html

  db:
    image: mysql:8.0
    container_name: lamp_db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123123
      - MYSQL_DATABASE=lamp_db
      - MYSQL_USER=lamp_db
      - MYSQL_PASSWORD=lamp_db
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: lamp_phpmyadmin
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=123123

volumes:
  db_data:
